name: run-tests

on: [push, pull_request, workflow_dispatch]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.1, 8.0, 7.4]
                dependency-version: [prefer-stable]

        name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Install dependencies
                run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
            
            -   name: List installed locales
                run: locale -a

            -   name: Execute tests
                run: ./vendor/bin/pest
